runtime: python39
entrypoint: gunicorn -b :$PORT app:app

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.8
  min_instances: 1
  max_instances: 5
  target_throughput_utilization: 0.8

env_variables:
  AIRTABLE_API_KEY: "pat58wdyhkYY9AaF9.c1ec6de961cb307900f1bfb3d274f69814b1942cec3055650d96190319d432a6"
  BASE_ID: "appr3XO1WxxZjPCJg"
  RESIDENTIAL_TABLE_NAME: "tblfADLQwmwUzuegD"
  COMMERCIAL_TABLE_NAME: "Commercial"
  INVENTORY_BASE_ID: "appjTVy4N5NFI7q0g"
  RESIDENTIAL_RENT_PROPERTIES_TABLE_ID: "tblJn9pCVgEwvFn2K"
